export const CATALOG = [
  {
    id: "ai",
    label: "AI düzenle",
    hints: [
      "Sadece ışığı değiştir",
      "Pencere manzarasını değiştir",
      "Bu nesneyi kaldır",
      "Malzemeyi daha lüks yap",
      "Rengi palete çek",
      "Aynı kare 2 varyasyon",
      "Daha net listing foto",
      "Akşam atmosferi",
      "Gündüz doğal ışık",
      "Mimariyi kilitle, stili değiştir",
    ],
  },
  {
    id: "furniture",
    label: "Mobilya",
    hints: [
      "Yemek sandalyelerini değiştir",
      "Yemek masasıni değiştir",
      "Komple yemek takımı",
      "Yemek takımı mutfakta kalsın",
      "Oturma grubunu değiştir",
      "Köşe takımına çevir",
      "İki berjer + kanepe",
      "Orta sehpa ahşap",
      "Orta sehpa mermer",
      "Orta sehpa cam",
      "TV ünitesini değiştir",
      "Konsolu kaldır",
    ],
  },
  {
    id: "concept",
    label: "Konsept",
    hints: [
      "Sıcak İstanbul salonu",
      "Minimal galeri",
      "Japandi sakin",
      "Boutique otel",
      "Modern klasik",
      "Scandi açık",
      "Ege yaz evi",
      "Ceviz + krem lüks",
      "Art deco hafif",
      "Wabi sabi sade",
    ],
  },
  {
    id: "color",
    label: "Renk",
    hints: [
      "Krem + ceviz",
      "Taş + zeytin",
      "Fildişi + pirinç",
      "Kum + antrasit",
      "Sıcak bej",
      "Kırık beyaz duvar",
      "Keten nötr",
      "Bronz vurgu",
      "Sage yeşil minder",
      "Grafit detay",
    ],
  },
  {
    id: "light",
    label: "Işık",
    hints: [
      "LED tavan kovu",
      "Gündüz pencere",
      "Akşam 2700K",
      "Tek sarkıt",
      "Halka avize",
      "Mutfak altı LED",
      "Raf içi LED",
      "Duvar yıkama",
      "Spot yok yumuşak",
      "Şehir ışığı dışarıda",
    ],
  },
  {
    id: "space",
    label: "Mimari",
    hints: [
      "Orijinal duvarlar kalsın",
      "Yeni niş/alan yok",
      "Buzdolabı mevcut mutfakta",
      "Balkon ekleme",
      "Pencere doğraması aynı",
      "Tavan aynı",
      "Klima gizle",
      "Zemin aynı",
      "Tek yemek masası",
      "Odaları birleştirme",
    ],
  },
  {
    id: "size",
    label: "Boyut",
    hints: ["9:16 dikey", "16:9 yatay", "1:1 kare", "4:3", "1 kare", "2 konsept", "2 açı"],
  },
  {
    id: "angle",
    label: "Açı",
    hints: [
      "Aynı kamera",
      "Uzak tam oda",
      "Normal göz hizası",
      "Yakın oturma",
      "Mutfağa bak",
      "Pencereye bak",
      "Köşeden",
      "Daha yüksek",
    ],
  },
  {
    id: "material",
    label: "Malzeme",
    hints: [
      "Bukle kumaş",
      "Keten",
      "Ceviz kaplama",
      "Traverten",
      "Meşe parke kalsın",
      "Mat lake",
      "Pirinç",
      "Keten halı",
      "Kadife minder",
      "Taş tezgâh",
    ],
  },
  {
    id: "style",
    label: "Tarz",
    hints: [
      "Daha minimal",
      "Daha lüks",
      "Daha sade",
      "Daha sıcak",
      "Daha erkek",
      "Daha dişil",
      "Daha genç",
      "Klasik vurgu",
      "Loft değil",
      "Katalog gibi olmasın",
    ],
  },
  {
    id: "quality",
    label: "Kalite",
    hints: [
      "Daha net fotoğraf",
      "Daha fotogerçek",
      "Listing kalitesi",
      "Daha az HDR",
      "Doğal gölge",
      "Malzeme dokusu belirgin",
      "Ucuz görünmesin",
      "Mimari doğru kalsın",
    ],
  },
  {
    id: "forbid",
    label: "Yapma",
    hints: [
      "Orijinal odaya sadık kal",
      "Odanın şeklini değiştirme",
      "Odaları birleştirme",
      "Ekstra koridor açma",
      "Balkon oluşturma",
      "İki açıyı birleştirme",
      "Yeni oda uydurma",
      "Duvar silme",
      "Pencere ekleme",
      "Tavan yüksekliğini değiştirme",
    ],
  },
] as const;

export type CatalogId = (typeof CATALOG)[number]["id"];
