/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as ArsivRouteImport } from './routes/arsiv'
import { Route as BolgelerRouteImport } from './routes/bolgeler'
import { Route as EntegrasyonRouteImport } from './routes/entegrasyon'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as HizmetlerRouteImport } from './routes/hizmetler'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as PortfoyRouteImport } from './routes/portfoy'
import { Route as SiteRouteImport } from './routes/site'
import { Route as SiteYonetimRouteImport } from './routes/site-yonetim'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as TaleplerRouteImport } from './routes/talepler'
import { Route as TekniklerRouteImport } from './routes/teknikler'
import { Route as PortfoyIdRouteImport } from './routes/portfoy.$id'
import { Route as ProjeIdRouteImport } from './routes/proje.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsivRoute = ArsivRouteImport.update({
  id: '/arsiv',
  path: '/arsiv',
  getParentRoute: () => rootRouteImport,
} as any)
const BolgelerRoute = BolgelerRouteImport.update({
  id: '/bolgeler',
  path: '/bolgeler',
  getParentRoute: () => rootRouteImport,
} as any)
const EntegrasyonRoute = EntegrasyonRouteImport.update({
  id: '/entegrasyon',
  path: '/entegrasyon',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerRoute = HizmetlerRouteImport.update({
  id: '/hizmetler',
  path: '/hizmetler',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoyRoute = PortfoyRouteImport.update({
  id: '/portfoy',
  path: '/portfoy',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteYonetimRoute = SiteYonetimRouteImport.update({
  id: '/site-yonetim',
  path: '/site-yonetim',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const TaleplerRoute = TaleplerRouteImport.update({
  id: '/talepler',
  path: '/talepler',
  getParentRoute: () => rootRouteImport,
} as any)
const TekniklerRoute = TekniklerRouteImport.update({
  id: '/teknikler',
  path: '/teknikler',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoyIdRoute = PortfoyIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortfoyRoute,
} as any)
const ProjeIdRoute = ProjeIdRouteImport.update({
  id: '/proje/$id',
  path: '/proje/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/arsiv': typeof ArsivRoute
  '/bolgeler': typeof BolgelerRoute
  '/entegrasyon': typeof EntegrasyonRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/portfoy': typeof PortfoyRouteWithChildren
  '/site': typeof SiteRoute
  '/site-yonetim': typeof SiteYonetimRoute
  '/studio': typeof StudioRoute
  '/talepler': typeof TaleplerRoute
  '/teknikler': typeof TekniklerRoute
  '/portfoy/$id': typeof PortfoyIdRoute
  '/proje/$id': typeof ProjeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/arsiv': typeof ArsivRoute
  '/bolgeler': typeof BolgelerRoute
  '/entegrasyon': typeof EntegrasyonRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/portfoy': typeof PortfoyRouteWithChildren
  '/site': typeof SiteRoute
  '/site-yonetim': typeof SiteYonetimRoute
  '/studio': typeof StudioRoute
  '/talepler': typeof TaleplerRoute
  '/teknikler': typeof TekniklerRoute
  '/portfoy/$id': typeof PortfoyIdRoute
  '/proje/$id': typeof ProjeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/arsiv': typeof ArsivRoute
  '/bolgeler': typeof BolgelerRoute
  '/entegrasyon': typeof EntegrasyonRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetler': typeof HizmetlerRoute
  '/iletisim': typeof IletisimRoute
  '/portfoy': typeof PortfoyRouteWithChildren
  '/site': typeof SiteRoute
  '/site-yonetim': typeof SiteYonetimRoute
  '/studio': typeof StudioRoute
  '/talepler': typeof TaleplerRoute
  '/teknikler': typeof TekniklerRoute
  '/portfoy/$id': typeof PortfoyIdRoute
  '/proje/$id': typeof ProjeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/arsiv'
    | '/bolgeler'
    | '/entegrasyon'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iletisim'
    | '/portfoy'
    | '/site'
    | '/site-yonetim'
    | '/studio'
    | '/talepler'
    | '/teknikler'
    | '/portfoy/$id'
    | '/proje/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/arsiv'
    | '/bolgeler'
    | '/entegrasyon'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iletisim'
    | '/portfoy'
    | '/site'
    | '/site-yonetim'
    | '/studio'
    | '/talepler'
    | '/teknikler'
    | '/portfoy/$id'
    | '/proje/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/arsiv'
    | '/bolgeler'
    | '/entegrasyon'
    | '/hakkimizda'
    | '/hizmetler'
    | '/iletisim'
    | '/portfoy'
    | '/site'
    | '/site-yonetim'
    | '/studio'
    | '/talepler'
    | '/teknikler'
    | '/portfoy/$id'
    | '/proje/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ArsivRoute: typeof ArsivRoute
  BolgelerRoute: typeof BolgelerRoute
  EntegrasyonRoute: typeof EntegrasyonRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  HizmetlerRoute: typeof HizmetlerRoute
  IletisimRoute: typeof IletisimRoute
  PortfoyRoute: typeof PortfoyRouteWithChildren
  SiteRoute: typeof SiteRoute
  SiteYonetimRoute: typeof SiteYonetimRoute
  StudioRoute: typeof StudioRoute
  TaleplerRoute: typeof TaleplerRoute
  TekniklerRoute: typeof TekniklerRoute
  ProjeIdRoute: typeof ProjeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsiv': {
      id: '/arsiv'
      path: '/arsiv'
      fullPath: '/arsiv'
      preLoaderRoute: typeof ArsivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bolgeler': {
      id: '/bolgeler'
      path: '/bolgeler'
      fullPath: '/bolgeler'
      preLoaderRoute: typeof BolgelerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entegrasyon': {
      id: '/entegrasyon'
      path: '/entegrasyon'
      fullPath: '/entegrasyon'
      preLoaderRoute: typeof EntegrasyonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetler': {
      id: '/hizmetler'
      path: '/hizmetler'
      fullPath: '/hizmetler'
      preLoaderRoute: typeof HizmetlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfoy': {
      id: '/portfoy'
      path: '/portfoy'
      fullPath: '/portfoy'
      preLoaderRoute: typeof PortfoyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site-yonetim': {
      id: '/site-yonetim'
      path: '/site-yonetim'
      fullPath: '/site-yonetim'
      preLoaderRoute: typeof SiteYonetimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talepler': {
      id: '/talepler'
      path: '/talepler'
      fullPath: '/talepler'
      preLoaderRoute: typeof TaleplerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teknikler': {
      id: '/teknikler'
      path: '/teknikler'
      fullPath: '/teknikler'
      preLoaderRoute: typeof TekniklerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfoy/$id': {
      id: '/portfoy/$id'
      path: '/$id'
      fullPath: '/portfoy/$id'
      preLoaderRoute: typeof PortfoyIdRouteImport
      parentRoute: typeof PortfoyRoute
    }
    '/proje/$id': {
      id: '/proje/$id'
      path: '/proje/$id'
      fullPath: '/proje/$id'
      preLoaderRoute: typeof ProjeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortfoyRouteChildren {
  PortfoyIdRoute: typeof PortfoyIdRoute
}

const PortfoyRouteChildren: PortfoyRouteChildren = {
  PortfoyIdRoute: PortfoyIdRoute,
}

const PortfoyRouteWithChildren =
  PortfoyRoute._addFileChildren(PortfoyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ArsivRoute: ArsivRoute,
  BolgelerRoute: BolgelerRoute,
  EntegrasyonRoute: EntegrasyonRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  HizmetlerRoute: HizmetlerRoute,
  IletisimRoute: IletisimRoute,
  PortfoyRoute: PortfoyRouteWithChildren,
  SiteRoute: SiteRoute,
  SiteYonetimRoute: SiteYonetimRoute,
  StudioRoute: StudioRoute,
  TaleplerRoute: TaleplerRoute,
  TekniklerRoute: TekniklerRoute,
  ProjeIdRoute: ProjeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
